version: '3.7'

services:
  
  product_db:
    image: postgres:latest
    container_name: product_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5440:5432"
    restart: always
    volumes:
      - product_db_data:/var/lib/postgresql/data/
volumes:
  product_db_data: